### ISSUE TITLE
Badges are too large

### ISSUE THREAD

**Issue by felixfbecker** [cssho/VSMarketplaceBadge#1]
See https://github.com/felixfbecker/vscode-php-debug, can we change the rating text to just "rating | 4.7/5 (25)" and maybe shorten "Visual Studio Marketplace" to "VS Marketplace"? Imo badges should be short and concise.

But thanks for the badges, they are awesome :)

**Comment by cssho** [comment]
Thanks @felixfbecker 
Add `version-short` badge and `rating-short` badge.
