### ISSUE TITLE
feature idea: rating with rating displayed as stars

### ISSUE THREAD

**Issue by Almenon** [cssho/VSMarketplaceBadge#11]
It would be cool if there was a badge with rating displayed visually as stars
> rating: ⭐⭐⭐⭐⭐

**Comment by cssho** [comment]
@Almenon 
I implemented your idea.

https://vsmarketplacebadge.apphb.com/rating-star/cssho.vscode-svgviewer.svg
![](https://vsmarketplacebadge.apphb.com/rating-star/cssho.vscode-svgviewer.svg)

**Comment by Almenon** [comment]
Awesome! :D  

Thanks man, I added it to my repo: https://github.com/Almenon/AREPL-vscode
