### ISSUE TITLE
Inconsistent Number of Installs

### ISSUE THREAD

**Issue by shree675** [cssho/VSMarketplaceBadge#19]
I have recently published an extension and it currently has 13 installs.
It shows correctly on the [website](https://vsmarketplacebadge.apphb.com/):

![image](https://user-images.githubusercontent.com/58718144/171581175-3db2e089-2b5f-4c93-aa8e-24416bbff94a.png)

But after copying the link to my README.md file, it shows the installs incorrectly:

![image](https://user-images.githubusercontent.com/58718144/171581418-93ba238f-b32f-489a-b0ca-42016022c371.png)

I have added the following code in my README.md file:
```md
<img src="https://vsmarketplacebadge.apphb.com/version-short/shree675.chalk-theme.svg"></img>&emsp;
<img src="https://vsmarketplacebadge.apphb.com/installs/shree675.chalk-theme.svg"></img>
```

Please let me know if I did something wrong. Any help is appreciated.

**Comment by cssho** [comment]
I think it has something to do with the behavior of the Microsoft API that is the data source and the GitHub cache (camo.githubusercontent.com). I reproduced the problem in my environment and was able to get the correct values by super reloading the browser.

**Comment by shree675** [comment]
I checked now and it seems to be working correctly on a different browser. It might be a problem with Chrome's cache. I'll maybe hard refresh the browser and try. Thanks.
