### ISSUE TITLE
When getting badges, return 500 in response

### ISSUE THREAD

**Issue by Huachao** [cssho/VSMarketplaceBadge#2]
You can see from my extension home page [VS Code REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)

**Comment by cssho** [comment]
VSMarketplaceBadge dependence on [shields.io](https://img.shields.io/) for SVG generate.
[shields.io](https://img.shields.io/) is down now.
I'll consider independence from [shields.io](https://img.shields.io/).
