### ISSUE TITLE
Better title for "installs" badge.

### ISSUE THREAD

**Issue by vpetrovykh** [cssho/VSMarketplaceBadge#3]
Great to finally have badges for VS marketplace! I am one of the authors of [MagicPython](https://marketplace.visualstudio.com/items?itemName=magicstack.MagicPython) extension for VS Code and would love to use your badge, but the issue is that our extension is actually available for Atom and Sublime Text 3 as well, so a plain "installs" title is not very informative. It would be great to have a way to provide a custom title for the installs badge.

**Comment by cssho** [comment]
You became able to set custom subject by query parameter(*subject*).

`https://vsmarketplacebadge.apphb.com/installs-short/magicstack.MagicPython.svg?subject=VSM`
![](https://vsmarketplacebadge.apphb.com/installs-short/magicstack.MagicPython.svg?subject=VSM)

ref b31ceefc7d712158f1be2563ca97f2d7d62fbe71

**Comment by vpetrovykh** [comment]
Thanks! That's great!
