### ISSUE TITLE
Add support for badge styles

### ISSUE THREAD

**Issue by idleberg** [cssho/VSMarketplaceBadge#4]
Shields badges offer a variety of styles, it would be nice if you would support them as well.

**Example:**

![Plastic](https://img.shields.io/badge/style-plastic-green.svg?style=plastic)
![Flat](https://img.shields.io/badge/style-flat-green.svg?style=flat)
![Flat Square](https://img.shields.io/badge/style-square-green.svg?style=flat-square)

**Code:**

```markdown
![Plastic](https://img.shields.io/badge/style-plastic-green.svg?style=plastic)
![Flat](https://img.shields.io/badge/style-flat-green.svg?style=flat)
![Flat Square](https://img.shields.io/badge/style-square-green.svg?style=flat-square)
```

**Comment by cssho** [comment]
@idleberg Support shields.io style & color.

**Comment by cssho** [comment]
Syupport shields.io color.
