### ISSUE TITLE
Badges seem to be broken

### ISSUE THREAD

**Issue by joshpeng** [cssho/VSMarketplaceBadge#5]
Seems like all the badges are broken.
https://vsmarketplacebadge.apphb.com/installs/joshpeng.sublime-babel-vscode.svg
http://vsmarketplacebadge.apphb.com/version/robertohuertasm.vscode-icons.svg

All of them return this:
```
<Error>
   <Message>An error has occurred.</Message>
</Error>
```

**Comment by cssho** [comment]
Thank you for a reporting.
There seems to be a change requiring User-Agent header to access Visual Studio Marketplace.
