### ISSUE TITLE
Default state instead of 404

### ISSUE THREAD

**Issue by felixfbecker** [cssho/VSMarketplaceBadge#7]
Just noticed that for unpublished extensions, the badge will return a 404:

![Latest Release](https://vsmarketplacebadge.apphb.com/version-short/sourcegraph.javascript-typescript.svg)

Most badges like Travis still return a badge:

![](https://api.travis-ci.org/sourcegraph/vscode-javascript-typescript.svg?branch=master)

**Comment by cssho** [comment]
I will implement it.

**Comment by cssho** [comment]
`https://vsmarketplacebadge.apphb.com/version-short/cssho.xxx.svg`

![Latest Release](https://vsmarketplacebadge.apphb.com/version-short/cssho.xxx.svg)
