### ISSUE TITLE
Use another file format

### ISSUE THREAD

**Issue by equinusocio** [cssho/VSMarketplaceBadge#8]
Packing vsix extension you can't now use .svg image anymore. So we an alternative file extension such .png or.gif

**Comment by cssho** [comment]
Support png and gif format

- https://vsmarketplacebadge.apphb.com/installs-short/cssho.vscode-svgviewer.svg

![](https://vsmarketplacebadge.apphb.com/installs-short/cssho.vscode-svgviewer.svg)

- https://vsmarketplacebadge.apphb.com/installs-short/cssho.vscode-svgviewer.png

![](https://vsmarketplacebadge.apphb.com/installs-short/cssho.vscode-svgviewer.png)

- https://vsmarketplacebadge.apphb.com/installs-short/cssho.vscode-svgviewer.gif

![](https://vsmarketplacebadge.apphb.com/installs-short/cssho.vscode-svgviewer.gif)

**Comment by equinusocio** [comment]
Ops sorry.

**Comment by cssho** [comment]
I didn't explain to you enough.
I looked at your issue and supported them at 0a7f40454c98ed860fa61e37f50651c1bdb2dc3c.
