### ISSUE TITLE
All Badge are broken

### ISSUE THREAD

**Issue by ritwickdey** [cssho/VSMarketplaceBadge#9]
Example : 
![broken badge](https://vsmarketplacebadge.apphb.com/rating/robertohuertasm.vscode-icons.svg)

https://vsmarketplacebadge.apphb.com/rating/robertohuertasm.vscode-icons.svg

![image](https://user-images.githubusercontent.com/18099464/32168876-32b4ac5e-bd94-11e7-8d13-f7aa89c854fd.png)

**Comment by ritwickdey** [comment]
Is this server issue? [Because this repo updated  2nd Oct.]

**Comment by cssho** [comment]
@ritwickdey
That is  caused by TLS problem for Shileds.io connection.
> The request was aborted: Could not create SSL/TLS secure channel.

Fixed at 4880d6a75345a2b22936ebc929e23b2464fc5994
